-- Permissions for the v2 external API. READ_STORE already exists.
ALTER TYPE "APIKeyPermission" ADD VALUE IF NOT EXISTS 'READ_SCHEDULE';
ALTER TYPE "APIKeyPermission" ADD VALUE IF NOT EXISTS 'WRITE_SCHEDULE';
ALTER TYPE "APIKeyPermission" ADD VALUE IF NOT EXISTS 'WRITE_STORE';
ALTER TYPE "APIKeyPermission" ADD VALUE IF NOT EXISTS 'READ_LIBRARY';
ALTER TYPE "APIKeyPermission" ADD VALUE IF NOT EXISTS 'RUN_AGENT';
ALTER TYPE "APIKeyPermission" ADD VALUE IF NOT EXISTS 'READ_RUN';
ALTER TYPE "APIKeyPermission" ADD VALUE IF NOT EXISTS 'WRITE_RUN';
ALTER TYPE "APIKeyPermission" ADD VALUE IF NOT EXISTS 'SHARE_RUN';
ALTER TYPE "APIKeyPermission" ADD VALUE IF NOT EXISTS 'READ_RUN_REVIEW';
ALTER TYPE "APIKeyPermission" ADD VALUE IF NOT EXISTS 'WRITE_RUN_REVIEW';
ALTER TYPE "APIKeyPermission" ADD VALUE IF NOT EXISTS 'READ_CREDITS';
ALTER TYPE "APIKeyPermission" ADD VALUE IF NOT EXISTS 'READ_FILES';
ALTER TYPE "APIKeyPermission" ADD VALUE IF NOT EXISTS 'WRITE_FILES';
