export const TIMEZONES = [
  { value: "UTC", label: "UTC (Coordinated Universal Time)" },
  { value: "America/Adak", label: "Adak (US - Aleutian Islands)" },
  { value: "America/Anchorage", label: "Anchorage (US - Alaska)" },
  { value: "America/Los_Angeles", label: "Los Angeles (US - Pacific)" },
  { value: "America/Tijuana", label: "Tijuana (Mexico - Pacific)" },
  { value: "America/Phoenix", label: "Phoenix (US - Arizona)" },
  { value: "America/Denver", label: "Denver (US - Mountain)" },
  { value: "America/Chicago", label: "Chicago (US - Central)" },
  { value: "America/New_York", label: "New York (US - Eastern)" },
  { value: "America/Toronto", label: "Toronto (Canada - Eastern)" },
  { value: "America/Halifax", label: "Halifax (Canada - Atlantic)" },
  { value: "America/St_Johns", label: "St. John's (Canada - Newfoundland)" },
  { value: "America/Caracas", label: "Caracas (Venezuela)" },
  { value: "America/Bogota", label: "Bogotá (Colombia)" },
  { value: "America/Lima", label: "Lima (Peru)" },
  { value: "America/Santiago", label: "Santiago (Chile)" },
  { value: "America/La_Paz", label: "La Paz (Bolivia)" },
  { value: "America/Asuncion", label: "Asunción (Paraguay)" },
  { value: "America/Montevideo", label: "Montevideo (Uruguay)" },
  { value: "America/Buenos_Aires", label: "Buenos Aires (Argentina)" },
  { value: "America/Sao_Paulo", label: "São Paulo (Brazil)" },
  { value: "America/Manaus", label: "Manaus (Brazil - Amazon)" },
  { value: "America/Fortaleza", label: "Fortaleza (Brazil - Northeast)" },
  { value: "America/Mexico_City", label: "Mexico City (Mexico)" },
  { value: "America/Guatemala", label: "Guatemala" },
  { value: "America/Costa_Rica", label: "Costa Rica" },
  { value: "America/Panama", label: "Panama" },
  { value: "America/Havana", label: "Havana (Cuba)" },
  { value: "America/Jamaica", label: "Jamaica" },
  { value: "America/Port-au-Prince", label: "Port-au-Prince (Haiti)" },
  {
    value: "America/Santo_Domingo",
    label: "Santo Domingo (Dominican Republic)",
  },
  { value: "America/Puerto_Rico", label: "Puerto Rico" },
  { value: "Atlantic/Azores", label: "Azores (Portugal)" },
  { value: "Atlantic/Cape_Verde", label: "Cape Verde" },
  { value: "Europe/London", label: "London (UK)" },
  { value: "Europe/Dublin", label: "Dublin (Ireland)" },
  { value: "Europe/Lisbon", label: "Lisbon (Portugal)" },
  { value: "Europe/Madrid", label: "Madrid (Spain)" },
  { value: "Europe/Paris", label: "Paris (France)" },
  { value: "Europe/Brussels", label: "Brussels (Belgium)" },
  { value: "Europe/Amsterdam", label: "Amsterdam (Netherlands)" },
  { value: "Europe/Berlin", label: "Berlin (Germany)" },
  { value: "Europe/Rome", label: "Rome (Italy)" },
  { value: "Europe/Vienna", label: "Vienna (Austria)" },
  { value: "Europe/Zurich", label: "Zurich (Switzerland)" },
  { value: "Europe/Prague", label: "Prague (Czech Republic)" },
  { value: "Europe/Warsaw", label: "Warsaw (Poland)" },
  { value: "Europe/Stockholm", label: "Stockholm (Sweden)" },
  { value: "Europe/Oslo", label: "Oslo (Norway)" },
  { value: "Europe/Copenhagen", label: "Copenhagen (Denmark)" },
  { value: "Europe/Helsinki", label: "Helsinki (Finland)" },
  { value: "Europe/Athens", label: "Athens (Greece)" },
  { value: "Europe/Bucharest", label: "Bucharest (Romania)" },
  { value: "Europe/Sofia", label: "Sofia (Bulgaria)" },
  { value: "Europe/Budapest", label: "Budapest (Hungary)" },
  { value: "Europe/Belgrade", label: "Belgrade (Serbia)" },
  { value: "Europe/Zagreb", label: "Zagreb (Croatia)" },
  { value: "Europe/Moscow", label: "Moscow (Russia)" },
  { value: "Europe/Kiev", label: "Kyiv (Ukraine)" },
  { value: "Europe/Istanbul", label: "Istanbul (Turkey)" },
  { value: "Asia/Dubai", label: "Dubai (UAE)" },
  { value: "Asia/Muscat", label: "Muscat (Oman)" },
  { value: "Asia/Kuwait", label: "Kuwait" },
  { value: "Asia/Riyadh", label: "Riyadh (Saudi Arabia)" },
  { value: "Asia/Baghdad", label: "Baghdad (Iraq)" },
  { value: "Asia/Tehran", label: "Tehran (Iran)" },
  { value: "Asia/Kabul", label: "Kabul (Afghanistan)" },
  { value: "Asia/Karachi", label: "Karachi (Pakistan)" },
  { value: "Asia/Tashkent", label: "Tashkent (Uzbekistan)" },
  { value: "Asia/Dhaka", label: "Dhaka (Bangladesh)" },
  { value: "Asia/Kolkata", label: "Kolkata (India)" },
  { value: "Asia/Kathmandu", label: "Kathmandu (Nepal)" },
  { value: "Asia/Colombo", label: "Colombo (Sri Lanka)" },
  { value: "Asia/Yangon", label: "Yangon (Myanmar)" },
  { value: "Asia/Bangkok", label: "Bangkok (Thailand)" },
  { value: "Asia/Ho_Chi_Minh", label: "Ho Chi Minh City (Vietnam)" },
  { value: "Asia/Jakarta", label: "Jakarta (Indonesia - Western)" },
  { value: "Asia/Makassar", label: "Makassar (Indonesia - Central)" },
  { value: "Asia/Jayapura", label: "Jayapura (Indonesia - Eastern)" },
  { value: "Asia/Manila", label: "Manila (Philippines)" },
  { value: "Asia/Singapore", label: "Singapore" },
  { value: "Asia/Kuala_Lumpur", label: "Kuala Lumpur (Malaysia)" },
  { value: "Asia/Hong_Kong", label: "Hong Kong" },
  { value: "Asia/Shanghai", label: "Shanghai (China)" },
  { value: "Asia/Taipei", label: "Taipei (Taiwan)" },
  { value: "Asia/Seoul", label: "Seoul (South Korea)" },
  { value: "Asia/Tokyo", label: "Tokyo (Japan)" },
  { value: "Asia/Vladivostok", label: "Vladivostok (Russia)" },
  { value: "Asia/Yakutsk", label: "Yakutsk (Russia)" },
  { value: "Asia/Irkutsk", label: "Irkutsk (Russia)" },
  { value: "Asia/Yekaterinburg", label: "Yekaterinburg (Russia)" },
  { value: "Australia/Perth", label: "Perth (Australia - Western)" },
  { value: "Australia/Darwin", label: "Darwin (Australia - Northern)" },
  { value: "Australia/Adelaide", label: "Adelaide (Australia - Central)" },
  { value: "Australia/Brisbane", label: "Brisbane (Australia - Eastern)" },
  { value: "Australia/Sydney", label: "Sydney (Australia - Eastern)" },
  { value: "Australia/Melbourne", label: "Melbourne (Australia - Eastern)" },
  { value: "Australia/Hobart", label: "Hobart (Australia - Eastern)" },
  { value: "Pacific/Auckland", label: "Auckland (New Zealand)" },
  { value: "Pacific/Fiji", label: "Fiji" },
  { value: "Pacific/Guam", label: "Guam" },
  { value: "Pacific/Honolulu", label: "Honolulu (US - Hawaii)" },
  { value: "Pacific/Samoa", label: "Samoa" },
  { value: "Pacific/Tahiti", label: "Tahiti (French Polynesia)" },
  { value: "Africa/Cairo", label: "Cairo (Egypt)" },
  { value: "Africa/Johannesburg", label: "Johannesburg (South Africa)" },
  { value: "Africa/Lagos", label: "Lagos (Nigeria)" },
  { value: "Africa/Nairobi", label: "Nairobi (Kenya)" },
  { value: "Africa/Casablanca", label: "Casablanca (Morocco)" },
  { value: "Africa/Algiers", label: "Algiers (Algeria)" },
  { value: "Africa/Tunis", label: "Tunis (Tunisia)" },
  { value: "Africa/Addis_Ababa", label: "Addis Ababa (Ethiopia)" },
  { value: "Africa/Dar_es_Salaam", label: "Dar es Salaam (Tanzania)" },
  { value: "Africa/Kampala", label: "Kampala (Uganda)" },
  { value: "Africa/Khartoum", label: "Khartoum (Sudan)" },
  { value: "Africa/Accra", label: "Accra (Ghana)" },
  { value: "Africa/Abidjan", label: "Abidjan (Ivory Coast)" },
  { value: "Africa/Dakar", label: "Dakar (Senegal)" },
];
