from auto_gpt.agent import Agent
from auto_gpt.agent_persist import AgentPersist

agent = AgentPersist()

# Train the agent
agent.train()

# Persist the agent to disk
agent.save()

# Load the agent from disk
agent_loader = AgentLoader()
agent = agent_loader.load()

# Use the agent to generate text
text = agent.generate("This is a sentence generated by a permanent agent.")
