# Date: 2023-5-20
# Author: Generated by GoCodeo.


from unittest.mock import patch

import pytest

from autogpt.commands.web_playwright import scrape_text


@pytest.fixture
def mock_sync_playwright(mocker):
    return mocker.patch("autogpt.commands.web_playwright.sync_playwright")


class TestScrapeText:
    def test_positive_scrape_text(self, mock_sync_playwright):
        mock_sync_playwright.return_value.__enter__.return_value.chromium.launch.return_value.new_page.return_value.content.return_value = """
        <html>
            <head>
                <title>Test Page</title>
            </head>
            <body>
                <h1>Hello, World!</h1>
                <p>This is a test page.</p>
            </body>
        </html>
        """
        url = "https://example.com"
        expected_text = "Test Page\nHello, World!\nThis is a test page."
        assert scrape_text(url) == expected_text

    def test_negative_scrape_text(self, mock_sync_playwright):
        mock_sync_playwright.return_value.__enter__.return_value.chromium.launch.return_value.new_page.return_value.goto.side_effect = Exception(
            "Error"
        )
        url = "https://invalid-url.com"
        expected_text = "Error: Error"
        assert scrape_text(url) == expected_text

    def test_edge_empty_page(self, mock_sync_playwright):
        mock_sync_playwright.return_value.__enter__.return_value.chromium.launch.return_value.new_page.return_value.content.return_value = (
            "<html></html>"
        )
        url = "https://empty-page.com"
        expected_text = ""
        assert scrape_text(url) == expected_text

    def test_edge_only_script_and_style(self, mock_sync_playwright):
        mock_sync_playwright.return_value.__enter__.return_value.chromium.launch.return_value.new_page.return_value.content.return_value = """
        <html>
            <head>
                <script>console.log("Test");</script>
                <style>body { background-color: red; }</style>
            </head>
            <body>
                <script>console.log("Another test");</script>
            </body>
        </html>
        """
        url = "https://script-style-only.com"
        expected_text = ""
        assert scrape_text(url) == expected_text
