#!/bin/bash

 ENV_PATH=$(poetry env info --path)
 if [ -d "$ENV_PATH" ]; then
     echo "Press ENTER to rm -rf $ENV_PATH"
     read && { rm -rf $ENV_PATH && echo "Removed the poetry environment at $ENV_PATH."; } || { echo "Please manually remove $ENV_PATH."; exit 1; }
 else
     echo "No poetry environment found."
 fi

 poetry install --extras benchmark
 echo "Setup completed successfully."
 exit 0
