Foreground yes
TCPSocket 3310
TCPAddr 127.0.0.1
DatabaseDirectory /data/clamav
LogFile /run/clamav/clamd.log
LogFileUnlock yes
LogFileMaxSize 50M
LogRotate yes
LogTime yes
PidFile /run/clamav/clamd.pid
User clamav
MaxFileSize 256M
MaxScanSize 512M
StreamMaxLength 256M
MaxThreads 10
SelfCheck 3600
ExitOnOOM yes
