DatabaseDirectory /data/clamav
DatabaseOwner clamav
UpdateLogFile /run/clamav/freshclam.log
LogFileMaxSize 50M
LogRotate yes
LogTime yes
Checks 12
Foreground yes
NotifyClamd /opt/autogpt/single-container/clamav/clamd.conf
DatabaseMirror database.clamav.net
ScriptedUpdates yes
CompressLocalDatabase no
TestDatabases yes
Bytecode yes
