/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * AutoGPT Agent Server
 * This server is used to execute agents that are created by the AutoGPT system.
 * OpenAPI spec version: 0.1
 */
import { z as zod } from "zod";

/**
 * @summary Get onboarding status
 */
export const getV1GetOnboardingStatusResponse = zod.any();

/**
 * @summary Update onboarding progress
 */
export const patchV1UpdateOnboardingProgressBody = zod.object({
  completedSteps: zod
    .array(
      zod.enum([
        "WELCOME",
        "USAGE_REASON",
        "INTEGRATIONS",
        "AGENT_CHOICE",
        "AGENT_NEW_RUN",
        "AGENT_INPUT",
        "CONGRATS",
        "GET_RESULTS",
        "RUN_AGENTS",
        "MARKETPLACE_VISIT",
        "MARKETPLACE_ADD_AGENT",
        "MARKETPLACE_RUN_AGENT",
        "BUILDER_OPEN",
        "BUILDER_SAVE_AGENT",
        "BUILDER_RUN_AGENT",
      ]),
    )
    .or(zod.null())
    .optional(),
  notificationDot: zod.boolean().or(zod.null()).optional(),
  notified: zod
    .array(
      zod.enum([
        "WELCOME",
        "USAGE_REASON",
        "INTEGRATIONS",
        "AGENT_CHOICE",
        "AGENT_NEW_RUN",
        "AGENT_INPUT",
        "CONGRATS",
        "GET_RESULTS",
        "RUN_AGENTS",
        "MARKETPLACE_VISIT",
        "MARKETPLACE_ADD_AGENT",
        "MARKETPLACE_RUN_AGENT",
        "BUILDER_OPEN",
        "BUILDER_SAVE_AGENT",
        "BUILDER_RUN_AGENT",
      ]),
    )
    .or(zod.null())
    .optional(),
  usageReason: zod.string().or(zod.null()).optional(),
  integrations: zod.array(zod.string()).or(zod.null()).optional(),
  otherIntegrations: zod.string().or(zod.null()).optional(),
  selectedStoreListingVersionId: zod.string().or(zod.null()).optional(),
  agentInput: zod.record(zod.string(), zod.any()).or(zod.null()).optional(),
  onboardingAgentExecutionId: zod.string().or(zod.null()).optional(),
  agentRuns: zod.number().or(zod.null()).optional(),
});

export const patchV1UpdateOnboardingProgressResponse = zod.any();

/**
 * @summary Get recommended agents
 */
export const getV1GetRecommendedAgentsResponse = zod.any();

/**
 * @summary Check onboarding enabled
 */
export const getV1CheckOnboardingEnabledResponse = zod.any();
