"""Auto-GPT: A GPT powered AI Assistant"""
import autogpt.cli

if __name__ == "__main__":
    
    # Import the necessary modules
from auto_gpt.agent import Agent
from auto_gpt.agent_persist import AgentPersist
from auto_gpt.agent_loader import AgentLoader

# Get the user's input
agent_type = input("Would you like to create a permanent or temporary agent? (p/t): ")

# Create the agent
if agent_type == "p":
    agent = AgentPersist()
elif agent_type == "t":
    agent = Agent()
else:
    print("Invalid input.")
    exit()

# Train the agent
agent.train()

# Use the agent to generate text
text = agent.generate("This is a sentence generated by a " + agent_type + " agent.")

# Print the generated text
print(text)

    autogpt.cli.main()
