project_id      = "agpt-dev"
region          = "us-central1"
zone            = "us-central1-a"
network_name    = "dev-gke-network"
subnet_name     = "dev-gke-subnet"
subnet_cidr     = "10.0.0.0/24"
cluster_name    = "dev-gke-cluster"
node_count      = 2
node_pool_name  = "dev-main-pool"
machine_type    = "e2-medium"
disk_size_gb    = 100
static_ip_names = ["agpt-server-ip", "agpt-builder-ip", "auth-ip"]
