/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * AutoGPT Agent Server
 * This server is used to execute agents that are created by the AutoGPT system.
 * OpenAPI spec version: 0.1
 */
import { z as zod } from "zod";

/**
 * @summary List available blocks
 */
export const getV1ListAvailableBlocksResponseItem = zod.record(
  zod.string(),
  zod.any(),
);
export const getV1ListAvailableBlocksResponse = zod.array(
  getV1ListAvailableBlocksResponseItem,
);

/**
 * @summary Execute graph block
 */
export const postV1ExecuteGraphBlockParams = zod.object({
  block_id: zod.string(),
});

export const postV1ExecuteGraphBlockBody = zod.record(zod.string(), zod.any());

export const postV1ExecuteGraphBlockResponse = zod.record(
  zod.string(),
  zod.array(zod.any()),
);
