/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * AutoGPT Agent Server
 * This server is used to execute agents that are created by the AutoGPT system.
 * OpenAPI spec version: 0.1
 */
import { z as zod } from "zod";

/**
 * Proxy requests to Otto API while adding necessary security headers and logging.
Requires an authenticated user.
 * @summary Proxy Otto Chat Request
 */
export const postV2ProxyOttoChatRequestBodyIncludeGraphDataDefault = false;

export const postV2ProxyOttoChatRequestBody = zod.object({
  query: zod.string(),
  conversation_history: zod.array(
    zod.object({
      query: zod.string(),
      response: zod.string(),
    }),
  ),
  message_id: zod.string(),
  include_graph_data: zod.boolean().optional(),
  graph_id: zod.string().or(zod.null()).optional(),
});

export const postV2ProxyOttoChatRequestResponse = zod.object({
  answer: zod.string(),
  documents: zod.array(
    zod.object({
      url: zod.string(),
      relevance_score: zod.number(),
    }),
  ),
  success: zod.boolean(),
});
