-- AlterEnum
ALTER TYPE "APIKeyPermission" ADD VALUE 'MANAGE_INTEGRATIONS';
ALTER TYPE "APIKeyPermission" ADD VALUE 'READ_INTEGRATIONS';
ALTER TYPE "APIKeyPermission" ADD VALUE 'DELETE_INTEGRATIONS';
