import plugin from "tailwindcss/plugin";

const autogptCustomTypographyPlugin = plugin(({ addComponents, theme }) => {
  addComponents({
    ".font-h1": {
      fontFamily: theme("fontFamily.poppin"),
      fontSize: "48px",
      fontWeight: theme("fontWeight.semibold"),
      lineHeight: "54px",
      letterSpacing: "-0.012em",
      color: "#020617",
    },
    ".font-h2": {
      fontFamily: theme("fontFamily.poppin"),
      fontSize: "35px",
      fontWeight: theme("fontWeight.medium"),
      lineHeight: "40px",
      letterSpacing: "-0.0075em",
      color: theme("colors.neutral.900"),
    },
    ".font-h3-poppins": {
      fontFamily: theme("fontFamily.poppin"),
      fontSize: "24px",
      fontWeight: theme("fontWeight.semibold"),
      lineHeight: "32px",
      letterSpacing: "-0.006em",
      color: "#282828",
    },
    ".font-h3-geist": {
      fontFamily: theme("fontFamily.sans"),
      fontSize: "24px",
      fontWeight: theme("fontWeight.normal"),
      lineHeight: "32px",
      letterSpacing: "-0.006em",
      color: theme("colors.neutral.700"),
    },
    ".font-h4": {
      fontFamily: theme("fontFamily.poppin"),
      fontSize: "20px",
      fontWeight: theme("fontWeight.medium"),
      lineHeight: "28px",
      letterSpacing: "-0.005em",
      color: "#020617",
    },
    ".font-large-poppins": {
      fontFamily: theme("fontFamily.poppin"),
      fontSize: "18px",
      fontWeight: theme("fontWeight.semibold"),
      lineHeight: "28px",
      color: "#020617",
    },
    ".font-large-geist": {
      fontFamily: theme("fontFamily.sans"),
      fontSize: "18px",
      fontWeight: theme("fontWeight.semibold"),
      lineHeight: "28px",
      color: "#020617",
    },
    ".font-lead": {
      fontFamily: theme("fontFamily.sans"),
      fontSize: "20px",
      fontWeight: theme("fontWeight.normal"),
      lineHeight: "28px",
      color: "#64748B",
    },
    ".font-lead-medium": {
      fontFamily: theme("fontFamily.sans"),
      fontSize: "20px",
      fontWeight: theme("fontWeight.medium"),
      lineHeight: "28px",
      color: "#64748B",
    },
    ".font-p": {
      fontFamily: theme("fontFamily.sans"),
      fontSize: "16px",
      fontWeight: theme("fontWeight.normal"),
      lineHeight: "28px",
      color: "#020617",
    },
    ".font-p-ui": {
      fontFamily: theme("fontFamily.sans"),
      fontSize: "16px",
      fontWeight: theme("fontWeight.normal"),
      lineHeight: "24px",
      color: "#525252",
    },
    ".font-p-medium": {
      fontFamily: theme("fontFamily.sans"),
      fontSize: "16px",
      fontWeight: theme("fontWeight.medium"),
      lineHeight: "28px",
      color: "#020617",
    },
    ".font-p-semibold": {
      fontFamily: theme("fontFamily.sans"),
      fontSize: "16px",
      fontWeight: theme("fontWeight.semibold"),
      lineHeight: "28px",
      color: "#020617",
    },
    ".font-list": {
      fontFamily: theme("fontFamily.inter"),
      fontSize: "16px",
      fontWeight: theme("fontWeight.normal"),
      lineHeight: "24px",
      color: "#020617",
    },
    ".font-body": {
      fontFamily: theme("fontFamily.sans"),
      fontSize: "14px",
      fontWeight: theme("fontWeight.normal"),
      lineHeight: "24px",
      color: "#020617",
    },
    ".font-body-medium": {
      fontFamily: theme("fontFamily.sans"),
      fontSize: "14px!important",
      fontWeight: theme("fontWeight.medium"),
      lineHeight: "24px",
      color: "#020617",
    },
    ".font-subtle": {
      fontFamily: theme("fontFamily.sans"),
      fontSize: "14px",
      fontWeight: theme("fontWeight.normal"),
      lineHeight: "20px",
      color: "#020617",
    },
    ".font-subtle-medium": {
      fontFamily: theme("fontFamily.sans"),
      fontSize: "14px",
      fontWeight: theme("fontWeight.medium"),
      lineHeight: "20px",
      color: "#020617",
    },
    ".font-subtle-semibold": {
      fontFamily: theme("fontFamily.sans"),
      fontSize: "14px",
      fontWeight: theme("fontWeight.semibold"),
      lineHeight: "20px",
      color: "#020617",
    },
    ".font-small": {
      fontFamily: theme("fontFamily.sans"),
      fontSize: "14px!important",
      fontWeight: theme("fontWeight.normal"),
      lineHeight: "14px",
      color: "#020617",
    },
    ".font-detail": {
      fontFamily: theme("fontFamily.sans"),
      fontSize: "12px",
      fontWeight: theme("fontWeight.medium"),
      lineHeight: "20px",
      color: "#020617",
    },
    ".font-inline-code": {
      fontFamily: theme("fontFamily.mono"),
      fontSize: "14px",
      fontWeight: theme("fontWeight.bold"),
      lineHeight: "20px",
      color: "#020617",
    },
  });
});

export default autogptCustomTypographyPlugin;
