/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * AutoGPT Agent Server
 * This server is used to execute agents that are created by the AutoGPT system.
 * OpenAPI spec version: 0.1
 */
import type { AccuracyLatestDataDailyScore } from "./accuracyLatestDataDailyScore";
import type { AccuracyLatestDataThreeDayAvg } from "./accuracyLatestDataThreeDayAvg";
import type { AccuracyLatestDataSevenDayAvg } from "./accuracyLatestDataSevenDayAvg";
import type { AccuracyLatestDataFourteenDayAvg } from "./accuracyLatestDataFourteenDayAvg";

/**
 * Latest execution accuracy data point.
 */
export interface AccuracyLatestData {
  date: Date;
  daily_score: AccuracyLatestDataDailyScore;
  three_day_avg: AccuracyLatestDataThreeDayAvg;
  seven_day_avg: AccuracyLatestDataSevenDayAvg;
  fourteen_day_avg: AccuracyLatestDataFourteenDayAvg;
}
