/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * AutoGPT Agent Server
 * This server is used to execute agents that are created by the AutoGPT system.
 * OpenAPI spec version: 0.1
 */
import type { ResponseType } from "./responseType";
import type { AgentOutputResponseSessionId } from "./agentOutputResponseSessionId";
import type { AgentOutputResponseLibraryAgentId } from "./agentOutputResponseLibraryAgentId";
import type { AgentOutputResponseLibraryAgentLink } from "./agentOutputResponseLibraryAgentLink";
import type { AgentOutputResponseExecution } from "./agentOutputResponseExecution";
import type { AgentOutputResponseAvailableExecutions } from "./agentOutputResponseAvailableExecutions";

/**
 * Response for agent_output tool.
 */
export interface AgentOutputResponse {
  type?: ResponseType;
  message: string;
  session_id?: AgentOutputResponseSessionId;
  agent_name: string;
  agent_id: string;
  library_agent_id?: AgentOutputResponseLibraryAgentId;
  library_agent_link?: AgentOutputResponseLibraryAgentLink;
  execution?: AgentOutputResponseExecution;
  available_executions?: AgentOutputResponseAvailableExecutions;
  total_executions?: number;
}
