/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * AutoGPT Agent Server
 * This server is used to execute agents that are created by the AutoGPT system.
 * OpenAPI spec version: 0.1
 */
import type { APIKeyStatus } from "./aPIKeyStatus";
import type { APIKeyPermission } from "./aPIKeyPermission";
import type { APIKeyWithoutHashLastUsedAt } from "./aPIKeyWithoutHashLastUsedAt";
import type { APIKeyWithoutHashRevokedAt } from "./aPIKeyWithoutHashRevokedAt";
import type { APIKeyWithoutHashDescription } from "./aPIKeyWithoutHashDescription";

export interface APIKeyWithoutHash {
  id: string;
  name: string;
  prefix: string;
  postfix: string;
  status: APIKeyStatus;
  permissions: APIKeyPermission[];
  created_at: string;
  last_used_at: APIKeyWithoutHashLastUsedAt;
  revoked_at: APIKeyWithoutHashRevokedAt;
  description: APIKeyWithoutHashDescription;
  user_id: string;
}
