/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * AutoGPT Agent Server
 * This server is used to execute agents that are created by the AutoGPT system.
 * OpenAPI spec version: 0.1
 */
import type { AuthorizeRequestCodeChallengeMethod } from "./authorizeRequestCodeChallengeMethod";

/**
 * OAuth 2.0 authorization request
 */
export interface AuthorizeRequest {
  /** Client identifier */
  client_id: string;
  /** Redirect URI */
  redirect_uri: string;
  /** List of scopes */
  scopes: string[];
  /** Anti-CSRF token from client */
  state: string;
  /** Must be 'code' for authorization code flow */
  response_type?: string;
  /** PKCE code challenge (required) */
  code_challenge: string;
  /** PKCE code challenge method (S256 recommended) */
  code_challenge_method?: AuthorizeRequestCodeChallengeMethod;
}
