/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * AutoGPT Agent Server
 * This server is used to execute agents that are created by the AutoGPT system.
 * OpenAPI spec version: 0.1
 */
import type { Node } from "./node";
import type { Link } from "./link";
import type { BaseGraphOutputForkedFromId } from "./baseGraphOutputForkedFromId";
import type { BaseGraphOutputForkedFromVersion } from "./baseGraphOutputForkedFromVersion";
import type { BaseGraphOutputInputSchema } from "./baseGraphOutputInputSchema";
import type { BaseGraphOutputOutputSchema } from "./baseGraphOutputOutputSchema";

export interface BaseGraphOutput {
  id?: string;
  version?: number;
  is_active?: boolean;
  name: string;
  description: string;
  nodes?: Node[];
  links?: Link[];
  forked_from_id?: BaseGraphOutputForkedFromId;
  forked_from_version?: BaseGraphOutputForkedFromVersion;
  readonly input_schema: BaseGraphOutputInputSchema;
  readonly output_schema: BaseGraphOutputOutputSchema;
}
