/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * AutoGPT Agent Server
 * This server is used to execute agents that are created by the AutoGPT system.
 * OpenAPI spec version: 0.1
 */
import type { BaseGraphInputInstructions } from "./baseGraphInputInstructions";
import type { BaseGraphInputRecommendedScheduleCron } from "./baseGraphInputRecommendedScheduleCron";
import type { BaseGraphInputForkedFromId } from "./baseGraphInputForkedFromId";
import type { BaseGraphInputForkedFromVersion } from "./baseGraphInputForkedFromVersion";
import type { Node } from "./node";
import type { Link } from "./link";

/**
 * Graph with nodes, links, and computed I/O schema fields.

Used to represent sub-graphs within a `Graph`. Contains the full graph
structure including nodes and links, plus computed fields for schemas
and trigger info. Does NOT include user_id or created_at (see GraphModel).
 */
export interface BaseGraphInput {
  id?: string;
  version?: number;
  is_active?: boolean;
  name: string;
  description: string;
  instructions?: BaseGraphInputInstructions;
  recommended_schedule_cron?: BaseGraphInputRecommendedScheduleCron;
  forked_from_id?: BaseGraphInputForkedFromId;
  forked_from_version?: BaseGraphInputForkedFromVersion;
  nodes?: Node[];
  links?: Link[];
}
