/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * AutoGPT Agent Server
 * This server is used to execute agents that are created by the AutoGPT system.
 * OpenAPI spec version: 0.1
 */
import type { BodyPostV2AddMarketplaceAgentSource } from "./bodyPostV2AddMarketplaceAgentSource";

export interface BodyPostV2AddMarketplaceAgent {
  store_listing_version_id: string;
  source?: BodyPostV2AddMarketplaceAgentSource;
}
