/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * AutoGPT Agent Server
 * This server is used to execute agents that are created by the AutoGPT system.
 * OpenAPI spec version: 0.1
 */
import type { BodyPostOauthRevokeTokenTypeHint } from "./bodyPostOauthRevokeTokenTypeHint";

export interface BodyPostOauthRevoke {
  /** Token to revoke */
  token: string;
  /** Hint about token type ('access_token' or 'refresh_token') */
  token_type_hint?: BodyPostOauthRevokeTokenTypeHint;
  /** Client identifier */
  client_id: string;
  /** Client secret */
  client_secret: string;
}
