/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * AutoGPT Agent Server
 * This server is used to execute agents that are created by the AutoGPT system.
 * OpenAPI spec version: 0.1
 */
import type { CreatorDetails } from "./creatorDetails";
import type { Pagination } from "./pagination";

export interface CreatorsResponse {
  creators: CreatorDetails[];
  pagination: Pagination;
}
