/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * AutoGPT Agent Server
 * This server is used to execute agents that are created by the AutoGPT system.
 * OpenAPI spec version: 0.1
 */
import type { CreateSessionResponseUserId } from "./createSessionResponseUserId";

/**
 * Response model containing information on a newly created chat session.
 */
export interface CreateSessionResponse {
  id: string;
  created_at: string;
  user_id: CreateSessionResponseUserId;
}
