/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * AutoGPT Agent Server
 * This server is used to execute agents that are created by the AutoGPT system.
 * OpenAPI spec version: 0.1
 */

export type CredentialsMetaInputType =
  (typeof CredentialsMetaInputType)[keyof typeof CredentialsMetaInputType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CredentialsMetaInputType = {
  api_key: "api_key",
  oauth2: "oauth2",
  user_password: "user_password",
  host_scoped: "host_scoped",
} as const;
