/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * AutoGPT Agent Server
 * This server is used to execute agents that are created by the AutoGPT system.
 * OpenAPI spec version: 0.1
 */
import type { CredentialsMetaInputTitle } from "./credentialsMetaInputTitle";
import type { CredentialsMetaInputType } from "./credentialsMetaInputType";

export interface CredentialsMetaInput {
  id: string;
  title?: CredentialsMetaInputTitle;
  /** Provider name for integrations. Can be any string value, including custom provider names. */
  provider: string;
  type: CredentialsMetaInputType;
}
