/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * AutoGPT Agent Server
 * This server is used to execute agents that are created by the AutoGPT system.
 * OpenAPI spec version: 0.1
 */
import type { MCPToolResponse } from "./mCPToolResponse";
import type { DiscoverToolsResponseServerName } from "./discoverToolsResponseServerName";
import type { DiscoverToolsResponseProtocolVersion } from "./discoverToolsResponseProtocolVersion";

/**
 * Response containing the list of tools available on an MCP server.
 */
export interface DiscoverToolsResponse {
  tools: MCPToolResponse[];
  server_name?: DiscoverToolsResponseServerName;
  protocol_version?: DiscoverToolsResponseProtocolVersion;
}
