/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * AutoGPT Agent Server
 * This server is used to execute agents that are created by the AutoGPT system.
 * OpenAPI spec version: 0.1
 */
import type { DocSearchResultDocUrl } from "./docSearchResultDocUrl";

/**
 * A single documentation search result.
 */
export interface DocSearchResult {
  title: string;
  path: string;
  section: string;
  snippet: string;
  score: number;
  doc_url?: DocSearchResultDocUrl;
}
