/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * AutoGPT Agent Server
 * This server is used to execute agents that are created by the AutoGPT system.
 * OpenAPI spec version: 0.1
 */
import type { ExecutionAnalyticsRequestGraphVersion } from "./executionAnalyticsRequestGraphVersion";
import type { ExecutionAnalyticsRequestUserId } from "./executionAnalyticsRequestUserId";
import type { ExecutionAnalyticsRequestCreatedAfter } from "./executionAnalyticsRequestCreatedAfter";
import type { ExecutionAnalyticsRequestSystemPrompt } from "./executionAnalyticsRequestSystemPrompt";
import type { ExecutionAnalyticsRequestUserPrompt } from "./executionAnalyticsRequestUserPrompt";

export interface ExecutionAnalyticsRequest {
  /** Graph ID to analyze */
  graph_id: string;
  /** Optional graph version */
  graph_version?: ExecutionAnalyticsRequestGraphVersion;
  /** Optional user ID filter */
  user_id?: ExecutionAnalyticsRequestUserId;
  /** Optional created date lower bound */
  created_after?: ExecutionAnalyticsRequestCreatedAfter;
  /** Model to use for generation */
  model_name?: string;
  /**
   * Batch size for concurrent processing
   * @minimum 1
   * @maximum 25
   */
  batch_size?: number;
  /** Custom system prompt (default: built-in prompt) */
  system_prompt?: ExecutionAnalyticsRequestSystemPrompt;
  /** Custom user prompt with {{GRAPH_NAME}} and {{EXECUTION_DATA}} placeholders (default: built-in prompt) */
  user_prompt?: ExecutionAnalyticsRequestUserPrompt;
  /** Whether to skip executions that already have activity status and correctness score */
  skip_existing?: boolean;
}
