/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * AutoGPT Agent Server
 * This server is used to execute agents that are created by the AutoGPT system.
 * OpenAPI spec version: 0.1
 */
import type { ExecutionOutputInfoStartedAt } from "./executionOutputInfoStartedAt";
import type { ExecutionOutputInfoEndedAt } from "./executionOutputInfoEndedAt";
import type { ExecutionOutputInfoOutputs } from "./executionOutputInfoOutputs";
import type { ExecutionOutputInfoInputsSummary } from "./executionOutputInfoInputsSummary";

/**
 * Summary of a single execution's outputs.
 */
export interface ExecutionOutputInfo {
  execution_id: string;
  status: string;
  started_at?: ExecutionOutputInfoStartedAt;
  ended_at?: ExecutionOutputInfoEndedAt;
  outputs: ExecutionOutputInfoOutputs;
  inputs_summary?: ExecutionOutputInfoInputsSummary;
}
