/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * AutoGPT Agent Server
 * This server is used to execute agents that are created by the AutoGPT system.
 * OpenAPI spec version: 0.1
 */
import type { FailedExecutionDetailUserEmail } from "./failedExecutionDetailUserEmail";
import type { FailedExecutionDetailStartedAt } from "./failedExecutionDetailStartedAt";
import type { FailedExecutionDetailFailedAt } from "./failedExecutionDetailFailedAt";
import type { FailedExecutionDetailErrorMessage } from "./failedExecutionDetailErrorMessage";

/**
 * Details about a failed execution for admin view
 */
export interface FailedExecutionDetail {
  execution_id: string;
  graph_id: string;
  graph_name: string;
  graph_version: number;
  user_id: string;
  user_email: FailedExecutionDetailUserEmail;
  status: string;
  created_at: Date;
  started_at: FailedExecutionDetailStartedAt;
  failed_at: FailedExecutionDetailFailedAt;
  error_message: FailedExecutionDetailErrorMessage;
}
