/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * AutoGPT Agent Server
 * This server is used to execute agents that are created by the AutoGPT system.
 * OpenAPI spec version: 0.1
 */
import type { FolderCreateRequestIcon } from "./folderCreateRequestIcon";
import type { FolderCreateRequestColor } from "./folderCreateRequestColor";
import type { FolderCreateRequestParentId } from "./folderCreateRequestParentId";

/**
 * Request model for creating a folder.
 */
export interface FolderCreateRequest {
  /**
   * @minLength 1
   * @maxLength 100
   */
  name: string;
  icon?: FolderCreateRequestIcon;
  /** Hex color code (#RRGGBB) */
  color?: FolderCreateRequestColor;
  parent_id?: FolderCreateRequestParentId;
}
