/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * AutoGPT Agent Server
 * This server is used to execute agents that are created by the AutoGPT system.
 * OpenAPI spec version: 0.1
 */

export type GetV1ListGraphExecutionsParams = {
  /**
   * Page number (1-indexed)
   * @minimum 1
   */
  page?: number;
  /**
   * Number of executions per page
   * @minimum 1
   * @maximum 100
   */
  page_size?: number;
};
