/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * AutoGPT Agent Server
 * This server is used to execute agents that are created by the AutoGPT system.
 * OpenAPI spec version: 0.1
 */
import type { GraphExecutionInputs } from "./graphExecutionInputs";
import type { GraphExecutionCredentialInputs } from "./graphExecutionCredentialInputs";
import type { GraphExecutionNodesInputMasks } from "./graphExecutionNodesInputMasks";
import type { GraphExecutionPresetId } from "./graphExecutionPresetId";
import type { AgentExecutionStatus } from "./agentExecutionStatus";
import type { GraphExecutionStats } from "./graphExecutionStats";
import type { GraphExecutionOutputs } from "./graphExecutionOutputs";

export interface GraphExecution {
  id: string;
  user_id: string;
  graph_id: string;
  graph_version: number;
  inputs: GraphExecutionInputs;
  credential_inputs: GraphExecutionCredentialInputs;
  nodes_input_masks: GraphExecutionNodesInputMasks;
  preset_id: GraphExecutionPresetId;
  status: AgentExecutionStatus;
  started_at: Date;
  ended_at: Date;
  stats: GraphExecutionStats;
  outputs: GraphExecutionOutputs;
}
