/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * AutoGPT Agent Server
 * This server is used to execute agents that are created by the AutoGPT system.
 * OpenAPI spec version: 0.1
 */

/**
 * Folder ID to move agent to (None to move to root)
 */
export type LibraryAgentUpdateRequestFolderId = string | null;
