/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * AutoGPT Agent Server
 * This server is used to execute agents that are created by the AutoGPT system.
 * OpenAPI spec version: 0.1
 */
import type { MCPToolInfoInputSchema } from "./mCPToolInfoInputSchema";

/**
 * Information about a single MCP tool discovered from a server.
 */
export interface MCPToolInfo {
  name: string;
  description: string;
  input_schema: MCPToolInfoInputSchema;
}
