/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * AutoGPT Agent Server
 * This server is used to execute agents that are created by the AutoGPT system.
 * OpenAPI spec version: 0.1
 */

export type OnboardingStep =
  (typeof OnboardingStep)[keyof typeof OnboardingStep];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OnboardingStep = {
  WELCOME: "WELCOME",
  USAGE_REASON: "USAGE_REASON",
  INTEGRATIONS: "INTEGRATIONS",
  AGENT_CHOICE: "AGENT_CHOICE",
  AGENT_NEW_RUN: "AGENT_NEW_RUN",
  AGENT_INPUT: "AGENT_INPUT",
  CONGRATS: "CONGRATS",
  VISIT_COPILOT: "VISIT_COPILOT",
  GET_RESULTS: "GET_RESULTS",
  MARKETPLACE_VISIT: "MARKETPLACE_VISIT",
  MARKETPLACE_ADD_AGENT: "MARKETPLACE_ADD_AGENT",
  MARKETPLACE_RUN_AGENT: "MARKETPLACE_RUN_AGENT",
  BUILDER_SAVE_AGENT: "BUILDER_SAVE_AGENT",
  RE_RUN_AGENT: "RE_RUN_AGENT",
  SCHEDULE_AGENT: "SCHEDULE_AGENT",
  RUN_AGENTS: "RUN_AGENTS",
  RUN_3_DAYS: "RUN_3_DAYS",
  TRIGGER_WEBHOOK: "TRIGGER_WEBHOOK",
  RUN_14_DAYS: "RUN_14_DAYS",
  RUN_AGENTS_100: "RUN_AGENTS_100",
  BUILDER_OPEN: "BUILDER_OPEN",
  BUILDER_RUN_AGENT: "BUILDER_RUN_AGENT",
} as const;
