/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * AutoGPT Agent Server
 * This server is used to execute agents that are created by the AutoGPT system.
 * OpenAPI spec version: 0.1
 */

/**
 * Response for onboarding status check.
 */
export interface OnboardingStatusResponse {
  is_onboarding_enabled: boolean;
  is_chat_enabled: boolean;
}
