/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * AutoGPT Agent Server
 * This server is used to execute agents that are created by the AutoGPT system.
 * OpenAPI spec version: 0.1
 */
import type { OrphanedScheduleDetailErrorDetail } from "./orphanedScheduleDetailErrorDetail";

/**
 * Details about an orphaned schedule
 */
export interface OrphanedScheduleDetail {
  schedule_id: string;
  schedule_name: string;
  graph_id: string;
  graph_version: number;
  user_id: string;
  orphan_reason: string;
  error_detail: OrphanedScheduleDetailErrorDetail;
  next_run_time: string;
}
