/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * AutoGPT Agent Server
 * This server is used to execute agents that are created by the AutoGPT system.
 * OpenAPI spec version: 0.1
 */
import type { PostmarkSubscriptionChangeWebhookMetadata } from "./postmarkSubscriptionChangeWebhookMetadata";

export interface PostmarkSubscriptionChangeWebhook {
  RecordType?: "SubscriptionChange";
  MessageID: string;
  ServerID: number;
  MessageStream: string;
  ChangedAt: string;
  Recipient: string;
  Origin: string;
  SuppressSending: boolean;
  SuppressionReason: string;
  Tag: string;
  Metadata: PostmarkSubscriptionChangeWebhookMetadata;
}
