/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * AutoGPT Agent Server
 * This server is used to execute agents that are created by the AutoGPT system.
 * OpenAPI spec version: 0.1
 */
import type { ProviderDetailsSource } from "./providerDetailsSource";
import type { ProviderDetailsSupportedCredentialTypesItem } from "./providerDetailsSupportedCredentialTypesItem";

export interface ProviderDetails {
  name: string;
  source: ProviderDetailsSource;
  has_oauth: boolean;
  has_webhooks: boolean;
  supported_credential_types?: ProviderDetailsSupportedCredentialTypesItem[];
}
