/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * AutoGPT Agent Server
 * This server is used to execute agents that are created by the AutoGPT system.
 * OpenAPI spec version: 0.1
 */

/**
 * Types of tool responses.
 */
export type ResponseType = (typeof ResponseType)[keyof typeof ResponseType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ResponseType = {
  agents_found: "agents_found",
  agent_details: "agent_details",
  setup_requirements: "setup_requirements",
  execution_started: "execution_started",
  need_login: "need_login",
  error: "error",
  no_results: "no_results",
  agent_output: "agent_output",
  understanding_updated: "understanding_updated",
  agent_builder_guide: "agent_builder_guide",
  agent_builder_preview: "agent_builder_preview",
  agent_builder_saved: "agent_builder_saved",
  agent_builder_clarification_needed: "agent_builder_clarification_needed",
  agent_builder_validation_result: "agent_builder_validation_result",
  agent_builder_fix_result: "agent_builder_fix_result",
  block_list: "block_list",
  block_details: "block_details",
  block_output: "block_output",
  doc_search_results: "doc_search_results",
  doc_page: "doc_page",
  workspace_file_list: "workspace_file_list",
  workspace_file_content: "workspace_file_content",
  workspace_file_metadata: "workspace_file_metadata",
  workspace_file_written: "workspace_file_written",
  workspace_file_deleted: "workspace_file_deleted",
  input_validation_error: "input_validation_error",
  web_fetch: "web_fetch",
  browser_navigate: "browser_navigate",
  browser_act: "browser_act",
  browser_screenshot: "browser_screenshot",
  bash_exec: "bash_exec",
  feature_request_search: "feature_request_search",
  feature_request_created: "feature_request_created",
  suggested_goal: "suggested_goal",
  mcp_guide: "mcp_guide",
  mcp_tools_discovered: "mcp_tools_discovered",
  mcp_tool_output: "mcp_tool_output",
  folder_created: "folder_created",
  folder_list: "folder_list",
  folder_updated: "folder_updated",
  folder_moved: "folder_moved",
  folder_deleted: "folder_deleted",
  agents_moved_to_folder: "agents_moved_to_folder",
} as const;
