/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * AutoGPT Agent Server
 * This server is used to execute agents that are created by the AutoGPT system.
 * OpenAPI spec version: 0.1
 */
import type { ReviewItemMessage } from "./reviewItemMessage";
import type { ReviewItemReviewedData } from "./reviewItemReviewedData";

/**
 * Single review item for processing.
 */
export interface ReviewItem {
  /** Node execution ID to review */
  node_exec_id: string;
  /** Whether this review is approved (True) or rejected (False) */
  approved: boolean;
  /** Optional review message */
  message?: ReviewItemMessage;
  /** Optional edited data (ignored if approved=False) */
  reviewed_data?: ReviewItemReviewedData;
  /** If true and this review is approved, future executions of this same block (node) will be automatically approved. This only affects approved reviews. */
  auto_approve_future?: boolean;
}
