/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * AutoGPT Agent Server
 * This server is used to execute agents that are created by the AutoGPT system.
 * OpenAPI spec version: 0.1
 */
import type { ReviewResponseError } from "./reviewResponseError";

/**
 * Response from review endpoint.
 */
export interface ReviewResponse {
  /** Number of reviews successfully approved */
  approved_count: number;
  /** Number of reviews successfully rejected */
  rejected_count: number;
  /** Number of reviews that failed processing */
  failed_count: number;
  /** Error message if operation failed */
  error?: ReviewResponseError;
}
