/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * AutoGPT Agent Server
 * This server is used to execute agents that are created by the AutoGPT system.
 * OpenAPI spec version: 0.1
 */
import type { SetupInfoRequirements } from "./setupInfoRequirements";
import type { UserReadiness } from "./userReadiness";

/**
 * Complete setup information.
 */
export interface SetupInfo {
  agent_id: string;
  agent_name: string;
  requirements?: SetupInfoRequirements;
  user_readiness?: UserReadiness;
}
