/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * AutoGPT Agent Server
 * This server is used to execute agents that are created by the AutoGPT system.
 * OpenAPI spec version: 0.1
 */

/**
 * Request model for stopping a single execution
 */
export interface StopExecutionRequest {
  execution_id: string;
}
