/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * AutoGPT Agent Server
 * This server is used to execute agents that are created by the AutoGPT system.
 * OpenAPI spec version: 0.1
 */
import type { StreamChatRequestContext } from "./streamChatRequestContext";
import type { StreamChatRequestFileIds } from "./streamChatRequestFileIds";

/**
 * Request model for streaming chat with optional context.
 */
export interface StreamChatRequest {
  message: string;
  is_user_message?: boolean;
  context?: StreamChatRequestContext;
  file_ids?: StreamChatRequestFileIds;
}
