/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * AutoGPT Agent Server
 * This server is used to execute agents that are created by the AutoGPT system.
 * OpenAPI spec version: 0.1
 */
import type { ResponseType } from "./responseType";
import type { SuggestedGoalResponseSessionId } from "./suggestedGoalResponseSessionId";
import type { SuggestedGoalResponseGoalType } from "./suggestedGoalResponseGoalType";

/**
 * Response when the goal needs refinement with a suggested alternative.
 */
export interface SuggestedGoalResponse {
  type?: ResponseType;
  message: string;
  session_id?: SuggestedGoalResponseSessionId;
  /** The suggested alternative goal */
  suggested_goal: string;
  /** Why the original goal needs refinement */
  reason?: string;
  /** The user's original goal for context */
  original_goal?: string;
  /** Type: 'vague' or 'unachievable' */
  goal_type?: SuggestedGoalResponseGoalType;
}
