/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * AutoGPT Agent Server
 * This server is used to execute agents that are created by the AutoGPT system.
 * OpenAPI spec version: 0.1
 */

export interface TokenRequestByRefreshToken {
  grant_type: "refresh_token";
  refresh_token: string;
  client_id: string;
  client_secret: string;
}
