/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * AutoGPT Agent Server
 * This server is used to execute agents that are created by the AutoGPT system.
 * OpenAPI spec version: 0.1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type { AuthorizeRequest } from "../../models/authorizeRequest";

import type { AuthorizeResponse } from "../../models/authorizeResponse";

import type { BodyPatchOauthUpdateAppStatus } from "../../models/bodyPatchOauthUpdateAppStatus";

import type { BodyPostOauthIntrospect } from "../../models/bodyPostOauthIntrospect";

import type { BodyPostOauthRevoke } from "../../models/bodyPostOauthRevoke";

import type { BodyPostOauthUploadAppLogo } from "../../models/bodyPostOauthUploadAppLogo";

import type { HTTP401NotAuthenticatedErrorResponse } from "../../models/hTTP401NotAuthenticatedErrorResponse";

import type { HTTPValidationError } from "../../models/hTTPValidationError";

import type { OAuthApplicationInfo } from "../../models/oAuthApplicationInfo";

import type { OAuthApplicationPublicInfo } from "../../models/oAuthApplicationPublicInfo";

import type { PostOauthTokenBody } from "../../models/postOauthTokenBody";

import type { TokenIntrospectionResult } from "../../models/tokenIntrospectionResult";

import type { TokenResponse } from "../../models/tokenResponse";

import type { UpdateAppLogoRequest } from "../../models/updateAppLogoRequest";

import { customMutator } from "../../../mutators/custom-mutator";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Get public information about an OAuth application.

This endpoint is used by the consent screen to display application details
to the user before they authorize access.

Returns:
- name: Application name
- description: Application description (if provided)
- scopes: List of scopes the application is allowed to request
 * @summary Get Oauth App Info
 */
export type getOauthGetOauthAppInfoResponse200 = {
  data: OAuthApplicationPublicInfo;
  status: 200;
};

export type getOauthGetOauthAppInfoResponse401 = {
  data: HTTP401NotAuthenticatedErrorResponse;
  status: 401;
};

export type getOauthGetOauthAppInfoResponse404 = {
  data: void;
  status: 404;
};

export type getOauthGetOauthAppInfoResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type getOauthGetOauthAppInfoResponseSuccess =
  getOauthGetOauthAppInfoResponse200 & {
    headers: Headers;
  };
export type getOauthGetOauthAppInfoResponseError = (
  | getOauthGetOauthAppInfoResponse401
  | getOauthGetOauthAppInfoResponse404
  | getOauthGetOauthAppInfoResponse422
) & {
  headers: Headers;
};

export type getOauthGetOauthAppInfoResponse =
  | getOauthGetOauthAppInfoResponseSuccess
  | getOauthGetOauthAppInfoResponseError;

export const getGetOauthGetOauthAppInfoUrl = (clientId: string) => {
  return `/api/oauth/app/${clientId}`;
};

export const getOauthGetOauthAppInfo = async (
  clientId: string,
  options?: RequestInit,
): Promise<getOauthGetOauthAppInfoResponse> => {
  return customMutator<getOauthGetOauthAppInfoResponse>(
    getGetOauthGetOauthAppInfoUrl(clientId),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetOauthGetOauthAppInfoQueryKey = (clientId?: string) => {
  return [`/api/oauth/app/${clientId}`] as const;
};

export const getGetOauthGetOauthAppInfoQueryOptions = <
  TData = Awaited<ReturnType<typeof getOauthGetOauthAppInfo>>,
  TError = HTTP401NotAuthenticatedErrorResponse | void | HTTPValidationError,
>(
  clientId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOauthGetOauthAppInfo>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customMutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetOauthGetOauthAppInfoQueryKey(clientId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getOauthGetOauthAppInfo>>
  > = ({ signal }) =>
    getOauthGetOauthAppInfo(clientId, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!clientId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getOauthGetOauthAppInfo>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetOauthGetOauthAppInfoQueryResult = NonNullable<
  Awaited<ReturnType<typeof getOauthGetOauthAppInfo>>
>;
export type GetOauthGetOauthAppInfoQueryError =
  | HTTP401NotAuthenticatedErrorResponse
  | void
  | HTTPValidationError;

export function useGetOauthGetOauthAppInfo<
  TData = Awaited<ReturnType<typeof getOauthGetOauthAppInfo>>,
  TError = HTTP401NotAuthenticatedErrorResponse | void | HTTPValidationError,
>(
  clientId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOauthGetOauthAppInfo>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOauthGetOauthAppInfo>>,
          TError,
          Awaited<ReturnType<typeof getOauthGetOauthAppInfo>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetOauthGetOauthAppInfo<
  TData = Awaited<ReturnType<typeof getOauthGetOauthAppInfo>>,
  TError = HTTP401NotAuthenticatedErrorResponse | void | HTTPValidationError,
>(
  clientId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOauthGetOauthAppInfo>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOauthGetOauthAppInfo>>,
          TError,
          Awaited<ReturnType<typeof getOauthGetOauthAppInfo>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetOauthGetOauthAppInfo<
  TData = Awaited<ReturnType<typeof getOauthGetOauthAppInfo>>,
  TError = HTTP401NotAuthenticatedErrorResponse | void | HTTPValidationError,
>(
  clientId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOauthGetOauthAppInfo>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Oauth App Info
 */

export function useGetOauthGetOauthAppInfo<
  TData = Awaited<ReturnType<typeof getOauthGetOauthAppInfo>>,
  TError = HTTP401NotAuthenticatedErrorResponse | void | HTTPValidationError,
>(
  clientId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOauthGetOauthAppInfo>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetOauthGetOauthAppInfoQueryOptions(
    clientId,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Get Oauth App Info
 */
export const prefetchGetOauthGetOauthAppInfoQuery = async <
  TData = Awaited<ReturnType<typeof getOauthGetOauthAppInfo>>,
  TError = HTTP401NotAuthenticatedErrorResponse | void | HTTPValidationError,
>(
  queryClient: QueryClient,
  clientId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOauthGetOauthAppInfo>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customMutator>;
  },
): Promise<QueryClient> => {
  const queryOptions = getGetOauthGetOauthAppInfoQueryOptions(
    clientId,
    options,
  );

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
};

/**
 * List all OAuth applications owned by the current user.

Returns a list of OAuth applications with their details including:
- id, name, description, logo_url
- client_id (public identifier)
- redirect_uris, grant_types, scopes
- is_active status
- created_at, updated_at timestamps

Note: client_secret is never returned for security reasons.
 * @summary List My Oauth Apps
 */
export type getOauthListMyOauthAppsResponse200 = {
  data: OAuthApplicationInfo[];
  status: 200;
};

export type getOauthListMyOauthAppsResponse401 = {
  data: HTTP401NotAuthenticatedErrorResponse;
  status: 401;
};

export type getOauthListMyOauthAppsResponseSuccess =
  getOauthListMyOauthAppsResponse200 & {
    headers: Headers;
  };
export type getOauthListMyOauthAppsResponseError =
  getOauthListMyOauthAppsResponse401 & {
    headers: Headers;
  };

export type getOauthListMyOauthAppsResponse =
  | getOauthListMyOauthAppsResponseSuccess
  | getOauthListMyOauthAppsResponseError;

export const getGetOauthListMyOauthAppsUrl = () => {
  return `/api/oauth/apps/mine`;
};

export const getOauthListMyOauthApps = async (
  options?: RequestInit,
): Promise<getOauthListMyOauthAppsResponse> => {
  return customMutator<getOauthListMyOauthAppsResponse>(
    getGetOauthListMyOauthAppsUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetOauthListMyOauthAppsQueryKey = () => {
  return [`/api/oauth/apps/mine`] as const;
};

export const getGetOauthListMyOauthAppsQueryOptions = <
  TData = Awaited<ReturnType<typeof getOauthListMyOauthApps>>,
  TError = HTTP401NotAuthenticatedErrorResponse,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getOauthListMyOauthApps>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customMutator>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetOauthListMyOauthAppsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getOauthListMyOauthApps>>
  > = ({ signal }) => getOauthListMyOauthApps({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getOauthListMyOauthApps>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetOauthListMyOauthAppsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getOauthListMyOauthApps>>
>;
export type GetOauthListMyOauthAppsQueryError =
  HTTP401NotAuthenticatedErrorResponse;

export function useGetOauthListMyOauthApps<
  TData = Awaited<ReturnType<typeof getOauthListMyOauthApps>>,
  TError = HTTP401NotAuthenticatedErrorResponse,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOauthListMyOauthApps>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOauthListMyOauthApps>>,
          TError,
          Awaited<ReturnType<typeof getOauthListMyOauthApps>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetOauthListMyOauthApps<
  TData = Awaited<ReturnType<typeof getOauthListMyOauthApps>>,
  TError = HTTP401NotAuthenticatedErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOauthListMyOauthApps>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOauthListMyOauthApps>>,
          TError,
          Awaited<ReturnType<typeof getOauthListMyOauthApps>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetOauthListMyOauthApps<
  TData = Awaited<ReturnType<typeof getOauthListMyOauthApps>>,
  TError = HTTP401NotAuthenticatedErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOauthListMyOauthApps>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List My Oauth Apps
 */

export function useGetOauthListMyOauthApps<
  TData = Awaited<ReturnType<typeof getOauthListMyOauthApps>>,
  TError = HTTP401NotAuthenticatedErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOauthListMyOauthApps>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetOauthListMyOauthAppsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary List My Oauth Apps
 */
export const prefetchGetOauthListMyOauthAppsQuery = async <
  TData = Awaited<ReturnType<typeof getOauthListMyOauthApps>>,
  TError = HTTP401NotAuthenticatedErrorResponse,
>(
  queryClient: QueryClient,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOauthListMyOauthApps>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customMutator>;
  },
): Promise<QueryClient> => {
  const queryOptions = getGetOauthListMyOauthAppsQueryOptions(options);

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
};

/**
 * Update the logo URL for an OAuth application.

Only the application owner can update the logo.
The logo should be uploaded first using the media upload endpoint,
then this endpoint is called with the resulting URL.

Logo requirements:
- Must be square (1:1 aspect ratio)
- Minimum 512x512 pixels
- Maximum 2048x2048 pixels

Returns the updated application info.
 * @summary Update App Logo
 */
export type patchOauthUpdateAppLogoResponse200 = {
  data: OAuthApplicationInfo;
  status: 200;
};

export type patchOauthUpdateAppLogoResponse401 = {
  data: HTTP401NotAuthenticatedErrorResponse;
  status: 401;
};

export type patchOauthUpdateAppLogoResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type patchOauthUpdateAppLogoResponseSuccess =
  patchOauthUpdateAppLogoResponse200 & {
    headers: Headers;
  };
export type patchOauthUpdateAppLogoResponseError = (
  | patchOauthUpdateAppLogoResponse401
  | patchOauthUpdateAppLogoResponse422
) & {
  headers: Headers;
};

export type patchOauthUpdateAppLogoResponse =
  | patchOauthUpdateAppLogoResponseSuccess
  | patchOauthUpdateAppLogoResponseError;

export const getPatchOauthUpdateAppLogoUrl = (appId: string) => {
  return `/api/oauth/apps/${appId}/logo`;
};

export const patchOauthUpdateAppLogo = async (
  appId: string,
  updateAppLogoRequest: UpdateAppLogoRequest,
  options?: RequestInit,
): Promise<patchOauthUpdateAppLogoResponse> => {
  return customMutator<patchOauthUpdateAppLogoResponse>(
    getPatchOauthUpdateAppLogoUrl(appId),
    {
      ...options,
      method: "PATCH",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(updateAppLogoRequest),
    },
  );
};

export const getPatchOauthUpdateAppLogoMutationOptions = <
  TError = HTTP401NotAuthenticatedErrorResponse | HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof patchOauthUpdateAppLogo>>,
    TError,
    { appId: string; data: UpdateAppLogoRequest },
    TContext
  >;
  request?: SecondParameter<typeof customMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof patchOauthUpdateAppLogo>>,
  TError,
  { appId: string; data: UpdateAppLogoRequest },
  TContext
> => {
  const mutationKey = ["patchOauthUpdateAppLogo"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof patchOauthUpdateAppLogo>>,
    { appId: string; data: UpdateAppLogoRequest }
  > = (props) => {
    const { appId, data } = props ?? {};

    return patchOauthUpdateAppLogo(appId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PatchOauthUpdateAppLogoMutationResult = NonNullable<
  Awaited<ReturnType<typeof patchOauthUpdateAppLogo>>
>;
export type PatchOauthUpdateAppLogoMutationBody = UpdateAppLogoRequest;
export type PatchOauthUpdateAppLogoMutationError =
  | HTTP401NotAuthenticatedErrorResponse
  | HTTPValidationError;

/**
 * @summary Update App Logo
 */
export const usePatchOauthUpdateAppLogo = <
  TError = HTTP401NotAuthenticatedErrorResponse | HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof patchOauthUpdateAppLogo>>,
      TError,
      { appId: string; data: UpdateAppLogoRequest },
      TContext
    >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof patchOauthUpdateAppLogo>>,
  TError,
  { appId: string; data: UpdateAppLogoRequest },
  TContext
> => {
  const mutationOptions = getPatchOauthUpdateAppLogoMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Upload a logo image for an OAuth application.

Requirements:
- Image must be square (1:1 aspect ratio)
- Minimum 512x512 pixels
- Maximum 2048x2048 pixels
- Allowed formats: JPEG, PNG, WebP
- Maximum file size: 3MB

The image is uploaded to cloud storage and the app's logoUrl is updated.
Returns the updated application info.
 * @summary Upload App Logo
 */
export type postOauthUploadAppLogoResponse200 = {
  data: OAuthApplicationInfo;
  status: 200;
};

export type postOauthUploadAppLogoResponse401 = {
  data: HTTP401NotAuthenticatedErrorResponse;
  status: 401;
};

export type postOauthUploadAppLogoResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type postOauthUploadAppLogoResponseSuccess =
  postOauthUploadAppLogoResponse200 & {
    headers: Headers;
  };
export type postOauthUploadAppLogoResponseError = (
  | postOauthUploadAppLogoResponse401
  | postOauthUploadAppLogoResponse422
) & {
  headers: Headers;
};

export type postOauthUploadAppLogoResponse =
  | postOauthUploadAppLogoResponseSuccess
  | postOauthUploadAppLogoResponseError;

export const getPostOauthUploadAppLogoUrl = (appId: string) => {
  return `/api/oauth/apps/${appId}/logo/upload`;
};

export const postOauthUploadAppLogo = async (
  appId: string,
  bodyPostOauthUploadAppLogo: BodyPostOauthUploadAppLogo,
  options?: RequestInit,
): Promise<postOauthUploadAppLogoResponse> => {
  const formData = new FormData();
  formData.append(`file`, bodyPostOauthUploadAppLogo.file);

  return customMutator<postOauthUploadAppLogoResponse>(
    getPostOauthUploadAppLogoUrl(appId),
    {
      ...options,
      method: "POST",
      body: formData,
    },
  );
};

export const getPostOauthUploadAppLogoMutationOptions = <
  TError = HTTP401NotAuthenticatedErrorResponse | HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postOauthUploadAppLogo>>,
    TError,
    { appId: string; data: BodyPostOauthUploadAppLogo },
    TContext
  >;
  request?: SecondParameter<typeof customMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postOauthUploadAppLogo>>,
  TError,
  { appId: string; data: BodyPostOauthUploadAppLogo },
  TContext
> => {
  const mutationKey = ["postOauthUploadAppLogo"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postOauthUploadAppLogo>>,
    { appId: string; data: BodyPostOauthUploadAppLogo }
  > = (props) => {
    const { appId, data } = props ?? {};

    return postOauthUploadAppLogo(appId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostOauthUploadAppLogoMutationResult = NonNullable<
  Awaited<ReturnType<typeof postOauthUploadAppLogo>>
>;
export type PostOauthUploadAppLogoMutationBody = BodyPostOauthUploadAppLogo;
export type PostOauthUploadAppLogoMutationError =
  | HTTP401NotAuthenticatedErrorResponse
  | HTTPValidationError;

/**
 * @summary Upload App Logo
 */
export const usePostOauthUploadAppLogo = <
  TError = HTTP401NotAuthenticatedErrorResponse | HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postOauthUploadAppLogo>>,
      TError,
      { appId: string; data: BodyPostOauthUploadAppLogo },
      TContext
    >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postOauthUploadAppLogo>>,
  TError,
  { appId: string; data: BodyPostOauthUploadAppLogo },
  TContext
> => {
  const mutationOptions = getPostOauthUploadAppLogoMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Enable or disable an OAuth application.

Only the application owner can update the status.
When disabled, the application cannot be used for new authorizations
and existing access tokens will fail validation.

Returns the updated application info.
 * @summary Update App Status
 */
export type patchOauthUpdateAppStatusResponse200 = {
  data: OAuthApplicationInfo;
  status: 200;
};

export type patchOauthUpdateAppStatusResponse401 = {
  data: HTTP401NotAuthenticatedErrorResponse;
  status: 401;
};

export type patchOauthUpdateAppStatusResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type patchOauthUpdateAppStatusResponseSuccess =
  patchOauthUpdateAppStatusResponse200 & {
    headers: Headers;
  };
export type patchOauthUpdateAppStatusResponseError = (
  | patchOauthUpdateAppStatusResponse401
  | patchOauthUpdateAppStatusResponse422
) & {
  headers: Headers;
};

export type patchOauthUpdateAppStatusResponse =
  | patchOauthUpdateAppStatusResponseSuccess
  | patchOauthUpdateAppStatusResponseError;

export const getPatchOauthUpdateAppStatusUrl = (appId: string) => {
  return `/api/oauth/apps/${appId}/status`;
};

export const patchOauthUpdateAppStatus = async (
  appId: string,
  bodyPatchOauthUpdateAppStatus: BodyPatchOauthUpdateAppStatus,
  options?: RequestInit,
): Promise<patchOauthUpdateAppStatusResponse> => {
  return customMutator<patchOauthUpdateAppStatusResponse>(
    getPatchOauthUpdateAppStatusUrl(appId),
    {
      ...options,
      method: "PATCH",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(bodyPatchOauthUpdateAppStatus),
    },
  );
};

export const getPatchOauthUpdateAppStatusMutationOptions = <
  TError = HTTP401NotAuthenticatedErrorResponse | HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof patchOauthUpdateAppStatus>>,
    TError,
    { appId: string; data: BodyPatchOauthUpdateAppStatus },
    TContext
  >;
  request?: SecondParameter<typeof customMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof patchOauthUpdateAppStatus>>,
  TError,
  { appId: string; data: BodyPatchOauthUpdateAppStatus },
  TContext
> => {
  const mutationKey = ["patchOauthUpdateAppStatus"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof patchOauthUpdateAppStatus>>,
    { appId: string; data: BodyPatchOauthUpdateAppStatus }
  > = (props) => {
    const { appId, data } = props ?? {};

    return patchOauthUpdateAppStatus(appId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PatchOauthUpdateAppStatusMutationResult = NonNullable<
  Awaited<ReturnType<typeof patchOauthUpdateAppStatus>>
>;
export type PatchOauthUpdateAppStatusMutationBody =
  BodyPatchOauthUpdateAppStatus;
export type PatchOauthUpdateAppStatusMutationError =
  | HTTP401NotAuthenticatedErrorResponse
  | HTTPValidationError;

/**
 * @summary Update App Status
 */
export const usePatchOauthUpdateAppStatus = <
  TError = HTTP401NotAuthenticatedErrorResponse | HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof patchOauthUpdateAppStatus>>,
      TError,
      { appId: string; data: BodyPatchOauthUpdateAppStatus },
      TContext
    >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof patchOauthUpdateAppStatus>>,
  TError,
  { appId: string; data: BodyPatchOauthUpdateAppStatus },
  TContext
> => {
  const mutationOptions = getPatchOauthUpdateAppStatusMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * OAuth 2.0 Authorization Endpoint

User must be logged in (authenticated with Supabase JWT).
This endpoint creates an authorization code and returns a redirect URL.

PKCE (Proof Key for Code Exchange) is REQUIRED for all authorization requests.

The frontend consent screen should call this endpoint after the user approves,
then redirect the user to the returned `redirect_url`.

Request Body:
- client_id: The OAuth application's client ID
- redirect_uri: Where to redirect after authorization (must match registered URI)
- scopes: List of permissions (e.g., "EXECUTE_GRAPH READ_GRAPH")
- state: Anti-CSRF token provided by client (will be returned in redirect)
- response_type: Must be "code" (for authorization code flow)
- code_challenge: PKCE code challenge (required)
- code_challenge_method: "S256" (recommended) or "plain"

Returns:
- redirect_url: The URL to redirect the user to (includes authorization code)

Error cases return a redirect_url with error parameters, or raise HTTPException
for critical errors (like invalid redirect_uri).
 * @summary Authorize
 */
export type postOauthAuthorizeResponse200 = {
  data: AuthorizeResponse;
  status: 200;
};

export type postOauthAuthorizeResponse401 = {
  data: HTTP401NotAuthenticatedErrorResponse;
  status: 401;
};

export type postOauthAuthorizeResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type postOauthAuthorizeResponseSuccess =
  postOauthAuthorizeResponse200 & {
    headers: Headers;
  };
export type postOauthAuthorizeResponseError = (
  | postOauthAuthorizeResponse401
  | postOauthAuthorizeResponse422
) & {
  headers: Headers;
};

export type postOauthAuthorizeResponse =
  | postOauthAuthorizeResponseSuccess
  | postOauthAuthorizeResponseError;

export const getPostOauthAuthorizeUrl = () => {
  return `/api/oauth/authorize`;
};

export const postOauthAuthorize = async (
  authorizeRequest: AuthorizeRequest,
  options?: RequestInit,
): Promise<postOauthAuthorizeResponse> => {
  return customMutator<postOauthAuthorizeResponse>(getPostOauthAuthorizeUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(authorizeRequest),
  });
};

export const getPostOauthAuthorizeMutationOptions = <
  TError = HTTP401NotAuthenticatedErrorResponse | HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postOauthAuthorize>>,
    TError,
    { data: AuthorizeRequest },
    TContext
  >;
  request?: SecondParameter<typeof customMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postOauthAuthorize>>,
  TError,
  { data: AuthorizeRequest },
  TContext
> => {
  const mutationKey = ["postOauthAuthorize"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postOauthAuthorize>>,
    { data: AuthorizeRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postOauthAuthorize(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostOauthAuthorizeMutationResult = NonNullable<
  Awaited<ReturnType<typeof postOauthAuthorize>>
>;
export type PostOauthAuthorizeMutationBody = AuthorizeRequest;
export type PostOauthAuthorizeMutationError =
  | HTTP401NotAuthenticatedErrorResponse
  | HTTPValidationError;

/**
 * @summary Authorize
 */
export const usePostOauthAuthorize = <
  TError = HTTP401NotAuthenticatedErrorResponse | HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postOauthAuthorize>>,
      TError,
      { data: AuthorizeRequest },
      TContext
    >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postOauthAuthorize>>,
  TError,
  { data: AuthorizeRequest },
  TContext
> => {
  const mutationOptions = getPostOauthAuthorizeMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * OAuth 2.0 Token Introspection Endpoint (RFC 7662)

Allows clients to check if a token is valid and get its metadata.

Returns:
- active: Whether the token is currently active
- scopes: List of authorized scopes (if active)
- client_id: The client the token was issued to (if active)
- user_id: The user the token represents (if active)
- exp: Expiration timestamp (if active)
- token_type: "access_token" or "refresh_token" (if active)
 * @summary Introspect
 */
export type postOauthIntrospectResponse200 = {
  data: TokenIntrospectionResult;
  status: 200;
};

export type postOauthIntrospectResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type postOauthIntrospectResponseSuccess =
  postOauthIntrospectResponse200 & {
    headers: Headers;
  };
export type postOauthIntrospectResponseError =
  postOauthIntrospectResponse422 & {
    headers: Headers;
  };

export type postOauthIntrospectResponse =
  | postOauthIntrospectResponseSuccess
  | postOauthIntrospectResponseError;

export const getPostOauthIntrospectUrl = () => {
  return `/api/oauth/introspect`;
};

export const postOauthIntrospect = async (
  bodyPostOauthIntrospect: BodyPostOauthIntrospect,
  options?: RequestInit,
): Promise<postOauthIntrospectResponse> => {
  return customMutator<postOauthIntrospectResponse>(
    getPostOauthIntrospectUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(bodyPostOauthIntrospect),
    },
  );
};

export const getPostOauthIntrospectMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postOauthIntrospect>>,
    TError,
    { data: BodyPostOauthIntrospect },
    TContext
  >;
  request?: SecondParameter<typeof customMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postOauthIntrospect>>,
  TError,
  { data: BodyPostOauthIntrospect },
  TContext
> => {
  const mutationKey = ["postOauthIntrospect"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postOauthIntrospect>>,
    { data: BodyPostOauthIntrospect }
  > = (props) => {
    const { data } = props ?? {};

    return postOauthIntrospect(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostOauthIntrospectMutationResult = NonNullable<
  Awaited<ReturnType<typeof postOauthIntrospect>>
>;
export type PostOauthIntrospectMutationBody = BodyPostOauthIntrospect;
export type PostOauthIntrospectMutationError = HTTPValidationError;

/**
 * @summary Introspect
 */
export const usePostOauthIntrospect = <
  TError = HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postOauthIntrospect>>,
      TError,
      { data: BodyPostOauthIntrospect },
      TContext
    >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postOauthIntrospect>>,
  TError,
  { data: BodyPostOauthIntrospect },
  TContext
> => {
  const mutationOptions = getPostOauthIntrospectMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * OAuth 2.0 Token Revocation Endpoint (RFC 7009)

Allows clients to revoke an access or refresh token.

Note: Revoking a refresh token does NOT revoke associated access tokens.
Revoking an access token does NOT revoke the associated refresh token.
 * @summary Revoke
 */
export type postOauthRevokeResponse200 = {
  data: unknown;
  status: 200;
};

export type postOauthRevokeResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type postOauthRevokeResponseSuccess = postOauthRevokeResponse200 & {
  headers: Headers;
};
export type postOauthRevokeResponseError = postOauthRevokeResponse422 & {
  headers: Headers;
};

export type postOauthRevokeResponse =
  | postOauthRevokeResponseSuccess
  | postOauthRevokeResponseError;

export const getPostOauthRevokeUrl = () => {
  return `/api/oauth/revoke`;
};

export const postOauthRevoke = async (
  bodyPostOauthRevoke: BodyPostOauthRevoke,
  options?: RequestInit,
): Promise<postOauthRevokeResponse> => {
  return customMutator<postOauthRevokeResponse>(getPostOauthRevokeUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(bodyPostOauthRevoke),
  });
};

export const getPostOauthRevokeMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postOauthRevoke>>,
    TError,
    { data: BodyPostOauthRevoke },
    TContext
  >;
  request?: SecondParameter<typeof customMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postOauthRevoke>>,
  TError,
  { data: BodyPostOauthRevoke },
  TContext
> => {
  const mutationKey = ["postOauthRevoke"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postOauthRevoke>>,
    { data: BodyPostOauthRevoke }
  > = (props) => {
    const { data } = props ?? {};

    return postOauthRevoke(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostOauthRevokeMutationResult = NonNullable<
  Awaited<ReturnType<typeof postOauthRevoke>>
>;
export type PostOauthRevokeMutationBody = BodyPostOauthRevoke;
export type PostOauthRevokeMutationError = HTTPValidationError;

/**
 * @summary Revoke
 */
export const usePostOauthRevoke = <
  TError = HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postOauthRevoke>>,
      TError,
      { data: BodyPostOauthRevoke },
      TContext
    >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postOauthRevoke>>,
  TError,
  { data: BodyPostOauthRevoke },
  TContext
> => {
  const mutationOptions = getPostOauthRevokeMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * OAuth 2.0 Token Endpoint

Exchanges authorization code or refresh token for access token.

Grant Types:
1. authorization_code: Exchange authorization code for tokens
   - Required: grant_type, code, redirect_uri, client_id, client_secret
   - Optional: code_verifier (required if PKCE was used)

2. refresh_token: Exchange refresh token for new access token
   - Required: grant_type, refresh_token, client_id, client_secret

Returns:
- access_token: Bearer token for API access (1 hour TTL)
- token_type: "Bearer"
- expires_in: Seconds until access token expires
- refresh_token: Token for refreshing access (30 days TTL)
- scopes: List of scopes
 * @summary Token
 */
export type postOauthTokenResponse200 = {
  data: TokenResponse;
  status: 200;
};

export type postOauthTokenResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type postOauthTokenResponseSuccess = postOauthTokenResponse200 & {
  headers: Headers;
};
export type postOauthTokenResponseError = postOauthTokenResponse422 & {
  headers: Headers;
};

export type postOauthTokenResponse =
  | postOauthTokenResponseSuccess
  | postOauthTokenResponseError;

export const getPostOauthTokenUrl = () => {
  return `/api/oauth/token`;
};

export const postOauthToken = async (
  postOauthTokenBody: PostOauthTokenBody,
  options?: RequestInit,
): Promise<postOauthTokenResponse> => {
  return customMutator<postOauthTokenResponse>(getPostOauthTokenUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(postOauthTokenBody),
  });
};

export const getPostOauthTokenMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postOauthToken>>,
    TError,
    { data: PostOauthTokenBody },
    TContext
  >;
  request?: SecondParameter<typeof customMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postOauthToken>>,
  TError,
  { data: PostOauthTokenBody },
  TContext
> => {
  const mutationKey = ["postOauthToken"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postOauthToken>>,
    { data: PostOauthTokenBody }
  > = (props) => {
    const { data } = props ?? {};

    return postOauthToken(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostOauthTokenMutationResult = NonNullable<
  Awaited<ReturnType<typeof postOauthToken>>
>;
export type PostOauthTokenMutationBody = PostOauthTokenBody;
export type PostOauthTokenMutationError = HTTPValidationError;

/**
 * @summary Token
 */
export const usePostOauthToken = <
  TError = HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postOauthToken>>,
      TError,
      { data: PostOauthTokenBody },
      TContext
    >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postOauthToken>>,
  TError,
  { data: PostOauthTokenBody },
  TContext
> => {
  const mutationOptions = getPostOauthTokenMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
